version: '3.9'

services:

  mysql:
    build: ./MySql/
    restart: always
    environment:
      MYSQL_DATABASE: 'testForDocker'
      MYSQL_ROOT_PASSWORD: 'pop'
    ports:
      - '3307:3306'
    volumes:
      - ./lib:/var/lib/mysql

volumes:
  lib:
